<a href="https://colab.research.google.com/github/AkashSeervi2003/PW_Assignment/blob/main/PythonAssignment06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***1)***

NumPy is a library in Python used for scientific computing and data analysis. It helps in handling large arrays and matrices efficiently.

**Purpose:**

* **Array Handling:** NumPy provides tools to create and manipulate large arrays and matrices.

* **Mathematical Functions**: It includes functions for performing mathematical operations on arrays.

***Advantages:***

* **Speed**: NumPy is faster than Python lists for numerical operations.

* **Memory Efficient:** It uses less memory compared to Python lists.

* **Vectorization:** Allows operations on entire arrays without loops, making code faster and easier to read.

* **Integration:** Works well with other libraries like Pandas and Matplotlib.

***Enhancing Python:***

* **Efficient Computations:** NumPy makes numerical computations faster and more efficient.

* **Array Operations:** Supports complex operations on arrays easily.
In summary, NumPy makes Python better for scientific computing by providing fast, memory-efficient tools for handling large arrays and performing mathematical operations.

# **2)**

np.mean() and np.average() are both used to calculate averages in NumPy, but they have some differences.

## **np.mean():**

**Purpose:** Calculates the simple average (arithmetic mean) of array elements.

**Usage:** np.mean(array)

**Weights:** Does not support weights; all elements are treated equally.

**Example:**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
print(mean_value)  # Output: 3.0

# **np.average():**

**Purpose**: Calculates the weighted average if weights are provided; otherwise, it calculates the simple average.

**Usage:** np.average(array, weights=weights)

**Weights:** Supports weights, allowing different importance to each element.

**Example:**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
weighted_avg = np.average(arr, weights=weights)
print(weighted_avg)  # Output: 3.67

**When to Use:**

* Use np.mean() for a simple average when all elements are equally important.
* Use np.average() for a weighted average when elements have different importance.

In summary, np.mean() is for simple averages, while np.average() is for weighted averages.

# **3)**
To reverse a NumPy array along different axes, you can use several methods. Here are the main ones:

# **1. Using np.flip():**

**Purpose:** Reverses the order of elements along the specified axis.

**Syntax:** np.flip(array, axis)

**Examples:**

* **1D Array:**



In [ ]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = np.flip(arr_1d)
print(reversed_1d)  # Output: [5 4 3 2 1]

* **2D Array:**

In [ ]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_2d_rows = np.flip(arr_2d, axis=0)  # Reverse rows
reversed_2d_cols = np.flip(arr_2d, axis=1)  # Reverse columns
print(reversed_2d_rows)  # Output: [[7 8 9] [4 5 6] [1 2 3]]
print(reversed_2d_cols)  # Output: [[3 2 1] [6 5 4] [9 8 7]]

# **2. Using Array Slicing:**

**Purpose:** Provides a simple way to reverse arrays using slicing.
**Syntax:** array[::-1] for reversing the entire array, or array[:, ::-1] for reversing along a specific axis.
**Examples:**

* **1D Array:**

In [ ]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]
print(reversed_1d)  # Output: [5 4 3 2 1

* **2D Array:**

In [ ]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_2d_rows = arr_2d[::-1, :]  # Reverse rows
reversed_2d_cols = arr_2d[:, ::-1]  # Reverse columns
print(reversed_2d_rows)  # Output: [[7 8 9] [4 5 6] [1 2 3]]
print(reversed_2d_cols)  # Output: [[3 2 1] [6 5 4] [9 8 7]]

In summary, np.flip() and array slicing are two effective methods to reverse NumPy arrays along different axes. Use np.flip() for more control over specific axes and array slicing for a quick and simple approach.

# **4)**

To determine the data type of elements in a NumPy array, you can use the dtype attribute. This attribute tells you the type of data stored in the array.

**Example:**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int32 (or another integer type depending on the system)

**Importance of Data Types:**

 1. **Memory Management:**

* **Efficient Memory Use:** Different data types use different amounts of memory. For example, an int32 uses 4 bytes, while an int64 uses 8 bytes. Choosing the right data type helps save memory.
* **Data Integrity:** Using the correct data type ensures that the data is stored accurately without loss of information.

2. **Performance:**

* **Speed:** Operations on smaller data types (like int32) are generally faster than on larger ones (like int64), because they require less memory and processing power.
* **Optimization:** Knowing the data type allows NumPy to optimize operations, making computations faster and more efficient.

In summary, determining the data type with dtype helps manage memory efficiently and improves performance by optimizing how data is stored and processed.

# **5)**

# **ndarrays in NumPy:**

**Definition:** An ndarray (N-dimensional array) is a multi-dimensional, fixed-size array in NumPy that holds elements of the same data type.

**Key Features:**

1. **Multi-Dimensional:** Can handle arrays with multiple dimensions (e.g., 1D, 2D, 3D).
2. **Homogeneous:** All elements must be of the same data type.
3. **Efficient Memory Use:** Stored in contiguous memory blocks, making operations faster.
4. **Vectorized Operations:** Supports element-wise operations without explicit loops.
5. **Indexing and Slicing:** Allows advanced indexing and slicing for accessing and modifying elements.

**Differences from Python Lists:**

1. **Data Type:** Lists can hold elements of different types; ndarrays require all elements to be the same type.
2. **Performance:** ndarrays are faster for numerical operations due to efficient memory use and vectorization.
3. **Memory:** ndarrays use less memory compared to lists for large datasets.
4. **Functionality:** ndarrays support more mathematical functions and operations than lists.

In summary, ndarrays are specialized for numerical and scientific computing, offering better performance and functionality compared to standard Python lists

# **6)**

NumPy arrays offer significant performance benefits over Python lists:

1. **Memory Efficiency**: NumPy arrays use less memory because they store data in contiguous blocks and have a fixed data type.
2. **Speed:** NumPy supports vectorized operations, which are faster than looping through Python lists.
3. **Optimized Implementation:** NumPy is implemented in C, making numerical operations faster.
**Example:**

In [ ]:
import numpy as np
import time

# Using NumPy array
arr = np.arange(1000000)
start_time = time.time()
np.sum(arr)
print("NumPy time:", time.time() - start_time)

# Using Python list
lst = list(range(1000000))
start_time = time.time()
sum(lst)
print("Python list time:", time.time() - start_time)

NumPy performs operations faster and uses memory more efficiently than Python lists.

# **7)**

vstack() and hstack() are functions in NumPy used to stack arrays vertically and horizontally, respectively.

***vstack():***

* **Purpose:** Stacks arrays in sequence vertically (row-wise).
* **Usage:** np.vstack((array1, array2, ...))
* **Example:**

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.vstack((a, b))
print(result)
# Output:
# [[1 2 3]
#  [4 5 6]]

***hstack():***

* **Purpose:** Stacks arrays in sequence horizontally (column-wise).
* **Usage:** np.hstack((array1, array2, ...))
* **Example:**

In [ ]:
import numpy as np
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
result = np.hstack((a, b))
print(result)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]

**Comparison:**

* **vstack()**: Adds arrays as new rows.

* **hstack()**: Adds arrays as new columns.

In summary, use vstack() to stack arrays vertically and hstack() to stack them horizontally

# **8)**

fliplr() and flipud() are functions in NumPy used to flip arrays, but they work in different directions.

**fliplr():**

* **Purpose**: Flips the array left to right (horizontally).

* **Effect**: Reverses the order of columns while keeping the rows the same.

* **Example**:

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.fliplr(arr)
print(result)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

**flipud():**

* **Purpose:** Flips the array up to down (vertically).

* **Effect:** Reverses the order of rows while keeping the columns the same.

* **Example:**

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.flipud(arr)
print(result)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

**Summary:**

**fliplr():** Flips horizontally, reversing columns.

**flipud():** Flips vertically, reversing rows.

In summary, use fliplr() to flip arrays left to right and flipud() to flip them up to down.

# **9)**

# **array_split():**

* **Purpose:** Splits an array into multiple sub-arrays.

* **Usage:** np.array_split(array, sections)

**Handling Uneven Splits:**

* **Uneven Division:** If the array cannot be evenly divided, array_split() creates sub-arrays of nearly equal size.

* **Example:**

In [ ]:
import numpy as np
arr = np.arange(9)
result = np.array_split(arr, 4)
print(result)
# Output: [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In this example, the array [0, 1, 2, 3, 4, 5, 6, 7, 8] is split into 4 parts. Since 9 elements cannot be evenly divided by 4, the first sub-array has 3 elements, and the rest have 2 elements each.

In summary, array_split() is useful for splitting arrays into nearly equal parts when an exact division is not possible.

# **10)**

**Vectorization:**

* **Definition:** Vectorization is the process of performing operations on entire arrays without using explicit loops.

* **Benefit:** It makes code faster and more efficient because operations are executed at once in low-level languages like C, instead of looping in Python.

**Example:**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2  # Multiplies each element by 2
print(result)  # Output: [2 4 6 8]

**Broadcasting:**

* **Definition:** Broadcasting allows NumPy to perform operations on arrays of different shapes by expanding the smaller array to match the shape of the larger one.

* **Benefit:** It enables efficient computation without making unnecessary copies of data.

* **Example:**

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
result = arr1 + arr2
print(result)
# Output:
# [[2 3 4]
#  [3 4 5]
#  [4 5 6]]

**Contribution to Efficient Array Operations:**

* **Speed:** Both vectorization and broadcasting eliminate the need for explicit loops, making operations faster.

* **Memory Efficiency**: Broadcasting avoids unnecessary data duplication, saving memory.

* **Simplified Code:** These techniques make code more concise and easier to read.

In summary, vectorization and broadcasting in NumPy enhance performance and efficiency by speeding up operations and reducing memory usage